version: "3.8"

services:
  admin:
    container_name: skripsi_admin
    build:
      context: .
      args:
        VITE_API_BASE_URL: https://api.strmlns.app/api
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:3100:80"  # internal only
